/*
 * Copyright (C) 2015 Man-gel
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */
package proy_casah;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.table.*;
import java.util.*;

/**
 *
 * @author Man-gel
 */
public class ChangeUsers extends javax.swing.JDialog {

    /**
     * Creates new form ChangeUsers
     */
    public ChangeUsers(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaUsuarios = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jToolBar1 = new javax.swing.JToolBar();
        avisoLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Lista Usuarios");

        modelo = BaseDatos.consultar("SELECT * FROM usuarios", 5, titulos);
        tablaUsuarios.setModel(modelo);
        tablaUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaUsuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaUsuarios);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Eliminar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("Editar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        avisoLbl.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        jToolBar1.add(avisoLbl);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(36, 36, 36))
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(continuar){
            int res = JOptionPane.showConfirmDialog(this,"¿Está seguro que desea eliminar este usuario?","Atención",JOptionPane.YES_NO_OPTION);
            if(res == JOptionPane.NO_OPTION || res == JOptionPane.CANCEL_OPTION )
                return;
            else{
            fila = tablaUsuarios.getSelectedRow();
            String[] registro = BaseDatos.consultarRegistro("SELECT * FROM usuarios WHERE user = '"+tablaUsuarios.getValueAt(fila, 1).toString()+"'", 5);
            String idSeleccionado = BaseDatos.consultarCampo("usuarios","id_usuario", "id_usuario", registro[0]);
            int afectadas = BaseDatos.borrar(Integer.parseInt(idSeleccionado), "usuarios", "id_usuario");
            avisoLbl.setText("ELIMINADOS: "+afectadas);
            }
        }        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(continuar){
            fila = tablaUsuarios.getSelectedRow();
            mostrarUsuarioSeleccionado(fila);
            Usuario users = new Usuario(new javax.swing.JFrame(),true);
            users.jButton1.setText("Guardar");
            users.jButton1.setEnabled(false);
            users.unombreOriginal = nom;
            users.userOriginal = us;
            users.passOriginal = p;
            users.permisosOriginal = perm;
            users.idOriginal = id;
            users.mostrarParaActualizar();
            users.setLocationRelativeTo(this);
            users.setVisible(true);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tablaUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaUsuariosMouseClicked
        for(int i = 0; i < tablaUsuarios.getRowCount(); i++)
            if(tablaUsuarios.isRowSelected(i)){
                continuar = true;
                break;
            }
        fila = tablaUsuarios.getSelectedRow();
        mostrarUsuarioSeleccionado(fila);
    }//GEN-LAST:event_tablaUsuariosMouseClicked
    
    private void mostrarUsuarioSeleccionado(int fila){
        nom = tablaUsuarios.getValueAt(fila, 2).toString();
        us = tablaUsuarios.getValueAt(fila, 1).toString();
        perm = tablaUsuarios.getValueAt(fila, 3).toString();
        id = tablaUsuarios.getValueAt(fila, 0).toString();
        p = BaseDatos.consultarCampo("usuarios","password","id_usuario",id);
    }
    
    private int fila;
    private DefaultTableModel modelo;
    private String[] titulos = {"No","User","Nombre","Permisos"};
    private String us;
    private String nom;
    private String perm;
    private String p;
    private String id = "";
    private Boolean continuar = false;
    private String usuarioSeleccionado[];
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel avisoLbl;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTable tablaUsuarios;
    // End of variables declaration//GEN-END:variables
}
