
package proy_casah;
import java.awt.event.KeyEvent;
import javafx.scene.input.KeyCode;
import javax.swing.*;
/**
 *
 * @author Man-gel
 */
public class Loggin extends java.awt.Frame {

    /**
     * Creates new form Loggin
     */
    public Loggin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        jLabel2 = new javax.swing.JLabel();
        passPF = new javax.swing.JPasswordField();
        userTF = new javax.swing.JTextField();
        button1 = new javax.swing.JButton();
        button2 = new javax.swing.JButton();

        setAlwaysOnTop(true);
        setLocationByPlatform(true);
        setResizable(false);
        setTitle("Loggin");
        setType(java.awt.Window.Type.UTILITY);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        panel1.setBackground(new java.awt.Color(0, 153, 153));

        label1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        label1.setText("Usuario");

        label2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        label2.setText("Contraseña");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginIcon.png"))); // NOI18N

        passPF.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        passPF.setNextFocusableComponent(button1);
        passPF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passPFKeyPressed(evt);
            }
        });

        userTF.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        userTF.setFocusCycleRoot(true);
        userTF.setNextFocusableComponent(passPF);

        button1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        button1.setText("Aceptar");
        button1.setNextFocusableComponent(button2);
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        button1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                button1KeyPressed(evt);
            }
        });

        button2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        button2.setText("Cancelar");
        button2.setNextFocusableComponent(userTF);
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addGap(161, 161, 161)
                                .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(panel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(10, 10, 10)))
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(passPF, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                            .addComponent(userTF)))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(button2)
                        .addGap(18, 18, 18)
                        .addComponent(button1)))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(88, 88, 88)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(userTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addComponent(passPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(39, 39, 39)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button1)
                    .addComponent(button2))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        add(panel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        this.dispose();
    }//GEN-LAST:event_exitForm

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        aceptar();
    }//GEN-LAST:event_button1ActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        this.exitForm(null);        
    }//GEN-LAST:event_button2ActionPerformed

    private void button1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_button1KeyPressed
        if(evt.getSource().equals(KeyCode.ENTER) || evt.getSource().equals(KeyCode.ACCEPT) ){
            aceptar();
        }
    }//GEN-LAST:event_button1KeyPressed

    private void passPFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passPFKeyPressed
        if(evt.getKeyCode()== KeyEvent.VK_ENTER)
            aceptar();
    }//GEN-LAST:event_passPFKeyPressed

    private void aceptar(){
        
        String us = userTF.getText();
        String pw = "";
        char pa[] = passPF.getPassword();
        if(us.isEmpty() && pa.length == 0)
        {
            JOptionPane.showMessageDialog(this, "Debe proporcionar sus datos de acceso");passPF.setText("");
            userTF.setText("");
            passPF.setText("");
            userTF.grabFocus();
            return;
        }            
        for(char let : pa){
            pw = pw + let;
        }
        if(Sis.textoInseguro(us) || Sis.textoInseguro(pw)){
            JOptionPane.showMessageDialog(this, "¿Qué intentas?\nAlgunos caracteres introducidos se consideran inseguros para el sistema: \n;  '  \"  \\");passPF.setText("");
            userTF.setText("");
            userTF.grabFocus();
            return;
        }
        String consulta[] = BaseDatos.consultarRegistro("SELECT * FROM usuarios WHERE user = '"+us+"'", 5);
        if(consulta[1] == null){
           JOptionPane.showMessageDialog(this, "El usuario y/o contraseña son incorrectos\n\n\nexc"); 
            passPF.setText("");
            userTF.setText("");
            userTF.grabFocus();            
            return;
        }
        if(consulta[1].equals(us) && consulta[4].equals(pw)){
            Principal.usuario = consulta[3];
            Principal.user = consulta[1];
            Principal.ini.doClick(100);
            this.exitForm(null);
        }else{
            JOptionPane.showMessageDialog(this, "El usuario y/o la contraseña son incorrectos");
            passPF.setText("");
            userTF.setText("");
            userTF.grabFocus();
            return;
        }
        
    }
    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button1;
    private javax.swing.JButton button2;
    private javax.swing.JLabel jLabel2;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Panel panel1;
    private javax.swing.JPasswordField passPF;
    private javax.swing.JTextField userTF;
    // End of variables declaration//GEN-END:variables
}
